services:

  app:
    image: niknak/server:latest
    container_name: app
    restart: always
    depends_on:
      app-db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8083/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      PORT: 8083
      NODE_ENV: development
      HOST: localhost
      COOKIE_SECRET: ''
      PUBLIC_URL: ''
    ports:
      - "8083:8083"
    networks:
      - niknak
    volumes:
      - ./server/entrypoint.sh:/entrypoint.sh
    entrypoint:
      - /entrypoint.sh

  ingestor:
    image: niknak/ingestor:latest
    container_name: ingestor
    restart: always
    profiles: [ingest]
    depends_on:
      app-db:
        condition: service_healthy
      app:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      PORT: 8084
      NODE_ENV: development
      HOST: localhost
      COOKIE_SECRET: ''
      PUBLIC_URL: ''
    ports:
      - "8084:8084"
    networks:
      - niknak
    volumes:
      - ./ingestor/entrypoint.sh:/entrypoint.sh
    entrypoint:
      - /entrypoint.sh

  migrations:
    image: niknak/server:latest
    depends_on:
      app-db:
        condition: service_healthy
    volumes:
      - ./migrations.sh:/migrations.sh
      - ./server/migrations:/usr/src/NikNakLocalStack/app/server/migrations
      - ../../NikNakPackages/packages/orm:/usr/src/NikNakPackages/packages/orm
    entrypoint:
      - /migrations.sh
    networks:
      - niknak

  app-db:
    image: postgres:16-alpine
    container_name: app-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: niknak
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d niknak"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - niknak

networks:
  niknak:
    external: true